[package]
name = "mktool"
description = "General purpose utility to enhance pkgsrc/mk infrastructure"
version = "1.0.1"
authors = ["Jonathan Perkin <jonathan@perkin.org.uk>"]
readme = "README.md"
keywords = ["pkgsrc"]
license = "ISC"
repository = "https://github.com/jperkin/mktool"
homepage = "https://github.com/jperkin/mktool"
documentation = "https://docs.rs/mktool"
rust-version = "1.74.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
elf = "0.7.4"
indicatif = "0.17.8"
pkgsrc = "0.1.32"
rayon = "1.10.0"
reqwest = { version = "0.12.7", features = ["blocking"] }
thiserror = "1.0.63"
